"""Run all three modes against the same data and write the comparison."""

from __future__ import annotations

from pathlib import Path

from .generate import ROWS_JOURNAL, build_source
from .modes import ModeRun, run_federate, run_replicate, run_share

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "data"
REPORTS = ROOT / "reports"


def run_all(repeats: int = 5, data_dir: Path | None = None) -> list[ModeRun]:
    """Each mode gets a pristine source, because each one ends by changing it.

    Rebuilding between modes is what keeps the staleness result meaningful: if the
    source still carried the previous mode's change, every mode would look fresh.
    """
    data = Path(data_dir) if data_dir else DATA
    source = data / "source.duckdb"
    runs = []
    for fn in (
        lambda: run_replicate(source, data / "wh_replicate.duckdb", repeats),
        lambda: run_federate(source, data / "wh_federate.duckdb", repeats),
        lambda: run_share(source, data / "wh_share.duckdb", data / "share", repeats),
    ):
        build_source(source)
        runs.append(fn())
    return runs


def render(runs: list[ModeRun]) -> str:
    rep = next(r for r in runs if r.mode == "REPLICATE")
    fed = next(r for r in runs if r.mode == "FEDERATE")
    shr = next(r for r in runs if r.mode == "SHARE")

    out: list[str] = []
    out.append("# Simulation — the three modes, actually executed\n")
    out.append(
        f"Generated by `make simulate`. The same consumer question — six periods of the "
        f"journal, joined to material master, grouped and ranked — answered three ways "
        f"against the same {ROWS_JOURNAL:,}-row synthetic source. Then one row is changed "
        f"in the source, and each mode is asked whether it noticed.\n"
    )
    out.append("## What this proves, and what it does not\n")
    out.append(
        "DuckDB plays both sides here: an attached read-only database is the SAP source, "
        "the working database is Snowflake, a Parquet file is the Delta-Sharing object. "
        "On one machine with one storage engine the **query times come out nearly "
        "identical by construction** — the real federation penalty is a network hop into "
        "a system that is also running the business, and no laptop reproduces that. Those "
        "milliseconds are printed below for completeness and should be ignored.\n"
    )
    out.append(
        "What survives the substitution is everything the modes actually differ in: what "
        "each one leaves at rest, what each one obliges you to operate, and which of them "
        "can see a change that was posted a second ago.\n"
    )
    out.append("## Measured\n")
    out.append(
        "| Mode | Setup | Recurring per tick | Warehouse at rest | Published once | "
        "Sees a change posted after setup | Query (ignore) |"
    )
    out.append("|---|---:|---:|---:|---:|:--:|---:|")
    for r in runs:
        out.append(
            f"| **{r.mode}** | {r.setup_seconds:,.2f}s | "
            f"{(f'{r.recurring_seconds:,.2f}s' if r.recurring_seconds else '—')} | "
            f"{r.warehouse_bytes / 1e6:,.1f} MB | "
            f"{(f'{r.published_bytes / 1e6:,.1f} MB' if r.published_bytes else '—')} | "
            f"{'yes' if r.sees_source_change else 'no'} | "
            f"{r.query_seconds_median * 1000:,.0f} ms |"
        )
    out.append("")
    out.append("## What each mode makes you own\n")
    for r in runs:
        out.append(f"- **{r.mode}** — {r.owns}. {r.detail}.")
    out.append("")
    out.append("## The three sentences worth taking away\n")
    out.append(
        f"1. **Replication is the only mode that leaves a second copy behind.** "
        f"{rep.warehouse_bytes / 1e6:,.1f} MB in the warehouse against "
        f"{fed.warehouse_bytes / 1e6:,.1f} MB for federation and "
        f"{shr.warehouse_bytes / 1e6:,.1f} MB for the share — and at the catalog's real "
        f"sizes that ratio is measured in terabytes and a monthly bill."
    )
    out.append(
        f"2. **Replication is also the only mode with a recurring job.** The delta upsert "
        f"took {rep.recurring_seconds:,.2f}s here and runs on every schedule tick forever; "
        f"the other two have no tick to run on, and therefore no 03:00 failure to "
        f"triage."
    )
    out.append(
        "3. **Only federation saw the change.** The share did not — it waits for the "
        "producer to republish — and the copy did not until its next delta run. A share "
        "is not federation with better economics; it is a copy someone else operates, "
        "and its freshness is their promise rather than your schedule.\n"
    )
    return "\n".join(out)


def main() -> None:
    runs = run_all()
    REPORTS.mkdir(parents=True, exist_ok=True)
    (REPORTS / "simulation.md").write_text(render(runs), encoding="utf-8")
    for r in runs:
        print(
            f"{r.mode:<10} setup {r.setup_seconds:>6.2f}s  "
            f"recurring {r.recurring_seconds:>6.2f}s  "
            f"warehouse {r.warehouse_bytes / 1e6:>7.1f} MB  "
            f"sees change: {'yes' if r.sees_source_change else 'no'}"
        )
    print(f"\nwrote {REPORTS / 'simulation.md'}")


if __name__ == "__main__":
    main()
