-- GENERATED by `sapbdc dbt-sources` — do not edit.
--
-- The decision engine assigned ACDOCA to SHARE under rule R6.
-- Everything downstream refs this model and therefore never names a mode:
-- flipping the decision changes this file and nothing in `marts/`.
--
-- Why: Zero-copy share, at a 1.18× premium over REPLICATE — accepted because this
-- object carries high business semantics (currency, hierarchies, CDS annotations)
-- that a replication flow flattens and someone then rebuilds in snowflake, at a cost
-- that never appears in the pipeline's bill.

select * from {{ ref('stg_journal__share') }}
