"""The register generates the dbt bindings — so a mode is a relation, not a comment.

A transformation layer that sits *next to* the decision engine is two boxes on a
diagram. This module joins them: the mode an object was assigned decides how that
object physically binds in dbt, and nothing else may declare a source.

Three files come out, all generated and none hand-edited (ADR-0007):

* ``models/staging/_sources.yml``          — one source per object that may cross
* ``models/staging/stg_journal__decided.sql`` — the binding the engine chose
* ``seeds/decision_register.csv``          — the register as data, so dbt can test it

The consequence worth stating plainly: an object the engine held in SAP gets **no
source at all**, and a model that selects from it fails to compile. R1 stops being
a paragraph and becomes a build failure at the place the violation would happen.

Generation is deterministic — no wall clock, no hash ordering — because CI gates
the committed output against a re-run (AGENTS.md rule 7).
"""

from __future__ import annotations

import csv
import io
import textwrap
from pathlib import Path

import yaml
from pydantic import BaseModel

from .catalog import CONFIG_DIR, Catalog, Mode, load_catalog
from .rules import Decision, decide_all

ROOT = Path(__file__).resolve().parents[2]
TRANSFORM_DIR = ROOT / "transform"

#: Stamped on every generated file. Deliberately names the command that rebuilds
#: it: a generated file whose header does not say how to regenerate it is a file
#: someone will eventually edit by hand.
_BANNER = (
    "# GENERATED by `sapbdc dbt-sources` — do not edit.\n"
    "#\n"
    "# Every source below is derived from the decision register: the integration\n"
    "# mode assigned to an object decides how that object binds here (ADR-0007).\n"
    "# Change `config/policy.yaml` or `config/objects.yaml`, run `make dbt-sources`,\n"
    "# and review the diff — that diff is the consequence of the policy change.\n"
)


class Binding(BaseModel):
    """How one integration mode lands as something dbt can select from."""

    source_name: str
    description: str
    database: str | None = None
    schema_name: str = "main"
    external_location: str | None = None


class BoundObject(BaseModel):
    table: str
    available_modes: list[Mode]


class TransformConfig(BaseModel):
    bindings: dict[Mode, Binding]
    mode_aliases: dict[Mode, Mode] = {}
    objects: dict[str, BoundObject]
    decided_journal_object: str

    def binding_mode(self, mode: Mode) -> Mode:
        """The mode whose binding a decision actually uses.

        HYBRID reads through its replicate leg: the aggregate the copy exists to
        serve. Its federated detail leg is a drill-down path, not the relation the
        marts are built on.
        """
        return self.mode_aliases.get(mode, mode)


def load_transform_config(config_dir: Path | None = None) -> TransformConfig:
    """Load ``config/transform.yaml``.

    Kept out of :func:`sapbdc.catalog.load_catalog` on purpose: this is not an
    input to the decision. It describes where a *decided* mode lands, which is a
    property of the runtime, and loading it alongside the estate would blur the
    line the whole repo is arranged around.
    """
    cfg = Path(config_dir) if config_dir else CONFIG_DIR
    with (cfg / "transform.yaml").open(encoding="utf-8") as fh:
        raw = yaml.safe_load(fh)

    bindings = {}
    for mode, spec in raw["bindings"].items():
        spec = dict(spec)
        spec["schema_name"] = spec.pop("schema", "main")
        bindings[Mode(mode)] = Binding.model_validate(spec)

    return TransformConfig(
        bindings=bindings,
        mode_aliases={Mode(k): Mode(v) for k, v in (raw.get("mode_aliases") or {}).items()},
        objects={k: BoundObject.model_validate(v) for k, v in raw["objects"].items()},
        decided_journal_object=raw["decided_journal_object"],
    )


def _held_in_sap(decisions: list[Decision]) -> list[Decision]:
    return [d for d in decisions if d.mode is Mode.KEEP_IN_SAP]


def sources_yml(decisions: list[Decision], cat: Catalog, tcfg: TransformConfig) -> str:
    """Render ``_sources.yml``: one dbt source group per mode, bound objects inside.

    An object is emitted only if the simulation materialises it *and* the engine
    let it cross the seam. Both halves matter — the first is a runtime fact, the
    second is a governance one, and conflating them is how a residency rule quietly
    stops being enforced.
    """
    by_id = {d.object_id: d for d in decisions}
    groups: dict[Mode, list[dict[str, object]]] = {}
    excluded: list[tuple[str, str]] = []

    for obj_id, bound in sorted(tcfg.objects.items()):
        decision = by_id.get(obj_id)
        if decision is None:
            raise ValueError(f"{obj_id} is bound in transform.yaml but not in the catalog")

        if decision.mode is Mode.KEEP_IN_SAP:
            excluded.append((obj_id, decision.primary_reason))
            continue

        catalog_obj = next(o for o in cat.objects if o.id == obj_id)
        for mode in bound.available_modes:
            # The source *group* carries the mode, so the table keeps its SAP name:
            # `source('sap_federated', 'acdoca')` reads as what it is.
            table = {
                "name": bound.table,
                "description": (
                    f"{catalog_obj.name} ({obj_id}) as it lands under {mode.value}."
                ),
                "meta": {
                    "object_id": obj_id,
                    "mode": mode.value,
                    "decided_mode": decision.mode.value,
                    "is_decided_binding": tcfg.binding_mode(decision.mode) is mode,
                    "rule_id": decision.rule_id,
                    "monthly_eur": round(decision.monthly_eur, 2),
                    "freshness_slo_minutes": catalog_obj.consumer.freshness_slo_minutes,
                },
            }
            groups.setdefault(mode, []).append(table)

    doc: dict[str, object] = {"version": 2, "sources": []}
    for mode in (Mode.REPLICATE, Mode.FEDERATE, Mode.SHARE):
        tables = groups.get(mode)
        if not tables:
            continue
        binding = tcfg.bindings[mode]
        source: dict[str, object] = {
            "name": binding.source_name,
            "description": " ".join(binding.description.split()),
            "schema": binding.schema_name,
        }
        if binding.database:
            source["database"] = binding.database
        if binding.external_location:
            # dbt-duckdb reads this instead of a relation name: the share is a file
            # the producer owns, not an object in your account.
            source["meta"] = {"external_location": binding.external_location}
        source["tables"] = tables
        doc["sources"].append(source)

    header = [_BANNER]
    if excluded:
        header.append(
            "#\n"
            "# Held in SAP by a constraint, and therefore deliberately absent below.\n"
            "# There is no source to select from, so a model that tries will not compile:\n"
        )
        header.extend(f"#   - {oid}: {reason.split(' — ')[0]}\n" for oid, reason in excluded)
    held = _held_in_sap(decisions)
    header.append(
        f"#\n# Register: {len(decisions)} objects, {len(held)} held in SAP, "
        f"{len(tcfg.objects) - len(excluded)} bound below.\n"
    )

    body = yaml.safe_dump(doc, sort_keys=False, width=88, allow_unicode=True)
    return "".join(header) + "\n" + body


def decided_model_sql(decisions: list[Decision], tcfg: TransformConfig) -> str:
    """Render the staging model that binds the journal to the mode that won.

    This is the file to look at first. It is three lines long and it is the entire
    argument: the marts ref *this*, so the mode is absorbed in staging and a policy
    change never reaches the semantic layer.
    """
    obj_id = tcfg.decided_journal_object
    decision = next((d for d in decisions if d.object_id == obj_id), None)
    if decision is None:
        raise ValueError(f"{obj_id} is not in the catalog")

    why = textwrap.fill(
        f"Why: {' '.join(decision.primary_reason.split()).rstrip('.')}.",
        width=86,
        initial_indent="-- ",
        subsequent_indent="-- ",
    )
    lead = (
        "-- GENERATED by `sapbdc dbt-sources` — do not edit.\n"
        "--\n"
        f"-- The decision engine assigned {obj_id} to {decision.mode.value} under rule "
        f"{decision.rule_id}.\n"
        "-- Everything downstream refs this model and therefore never names a mode:\n"
        "-- flipping the decision changes this file and nothing in `marts/`.\n"
        "--\n"
        f"{why}\n"
        "\n"
    )

    if decision.mode is Mode.KEEP_IN_SAP:
        # Not an error in the generator — a correct outcome, expressed where it has
        # to be enforced. The build stops, and it stops with the reason attached.
        return (
            lead
            + "{{ exceptions.raise_compiler_error(\n"
            f"    \"{obj_id} is KEEP_IN_SAP: no data may cross the seam, so there is no \"\n"
            "    \"relation to model. Model it inside SAP, or change the constraint that \"\n"
            f"    \"held it — rule {decision.rule_id}.\"\n"
            ") }}\n"
        )

    binding_mode = tcfg.binding_mode(decision.mode)
    ref = f"stg_journal__{binding_mode.value.lower()}"
    note = ""
    if binding_mode is not decision.mode:
        note = (
            f"-- {decision.mode.value} reads through its {binding_mode.value} leg: the "
            f"aggregate the copy\n-- exists to serve. The federated detail leg is a "
            f"drill-down path, not this model.\n"
        )

    return f"{lead}{note}select * from {{{{ ref('{ref}') }}}}\n"


def register_seed_csv(decisions: list[Decision], cat: Catalog) -> str:
    """The whole register as a seed, so dbt tests can assert against the decision.

    Seeding it is what lets ``assert_no_source_is_kept_in_sap`` be a real test
    rather than a convention: the graph's sources are checked against the same
    decisions the register printed, inside the build that would use them.
    """
    by_id = {o.id: o for o in cat.objects}
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(
        [
            "object_id",
            "object_name",
            "domain",
            "direction",
            "mode",
            "rule_id",
            "monthly_eur",
            "size_gb",
            "queries_per_day",
            "freshness_slo_minutes",
            "crossover_queries_per_day",
        ]
    )
    for d in decisions:
        obj = by_id[d.object_id]
        writer.writerow(
            [
                d.object_id,
                d.object_name,
                d.domain,
                d.direction,
                d.mode.value,
                d.rule_id,
                f"{d.monthly_eur:.2f}",
                f"{obj.size_gb:.1f}",
                f"{obj.consumer.queries_per_day:.0f}",
                f"{obj.consumer.freshness_slo_minutes:.0f}",
                ""
                if d.crossover_queries_per_day is None
                else f"{d.crossover_queries_per_day:.2f}",
            ]
        )
    return buf.getvalue()


def write_all(
    decisions: list[Decision],
    cat: Catalog,
    tcfg: TransformConfig,
    transform_dir: Path | None = None,
) -> list[Path]:
    out = Path(transform_dir) if transform_dir else TRANSFORM_DIR
    staging = out / "models" / "staging"
    seeds = out / "seeds"
    staging.mkdir(parents=True, exist_ok=True)
    seeds.mkdir(parents=True, exist_ok=True)

    written = []
    for path, content in (
        (staging / "_sources.yml", sources_yml(decisions, cat, tcfg)),
        (staging / "stg_journal__decided.sql", decided_model_sql(decisions, tcfg)),
        (seeds / "decision_register.csv", register_seed_csv(decisions, cat)),
    ):
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def generate(
    config_dir: Path | None = None, transform_dir: Path | None = None
) -> list[Path]:
    cat = load_catalog(config_dir)
    return write_all(decide_all(cat), cat, load_transform_config(config_dir), transform_dir)


__all__ = [
    "Binding",
    "BoundObject",
    "TransformConfig",
    "decided_model_sql",
    "generate",
    "load_transform_config",
    "register_seed_csv",
    "sources_yml",
    "write_all",
]
