"""Rendering — the console summary, the decision register, and the crossover chart.

The decision register (``reports/decisions.md``) is the artifact you hand to the
people who have to live with the choices. It is deliberately one row per object
with the *reason* in the row: a table of modes without reasons is a table nobody
can challenge, and a decision nobody can challenge is a decision nobody owns.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

from .catalog import Catalog, Mode
from .econ import DAYS_PER_MONTH, cost_curve, crossover_queries_per_day
from .rules import Decision

REPORTS = Path(__file__).resolve().parents[2] / "reports"

_MODE_ORDER = [Mode.SHARE, Mode.REPLICATE, Mode.FEDERATE, Mode.HYBRID, Mode.KEEP_IN_SAP]


def console_summary(decisions: list[Decision], cat: Catalog) -> str:
    lines: list[str] = []
    w = max(len(d.object_id) for d in decisions)
    lines.append(f"CATALOG: {len(decisions)} objects · target {cat.landscape.target.platform} "
                 f"({cat.landscape.target.region})")
    lines.append("")
    header = (
        f"{'OBJECT'.ljust(w)}  {'SIZE':>9}  {'DELTA':>6}  {'Q/DAY':>7}  "
        f"{'MODE':<12} {'€/MONTH':>9}  WHY"
    )
    lines.append(header)
    lines.append("-" * len(header))
    by_id = {o.id: o for o in cat.objects}
    for d in decisions:
        obj = by_id[d.object_id]
        why = d.primary_reason.split(" — ")[0].split(": ")[0]
        lines.append(
            f"{d.object_id.ljust(w)}  {obj.size_gb:>8,.1f}G  "
            f"{obj.delta_capability:>6}  {obj.consumer.queries_per_day:>7,.0f}  "
            f"{d.mode.value:<12} {d.monthly_eur:>9,.0f}  [{d.rule_id}] {why[:52]}"
        )
    lines.append("")

    counts = Counter(d.mode for d in decisions)
    mix = "  ".join(f"{m.value}: {counts.get(m, 0)}" for m in _MODE_ORDER)
    lines.append(f"MIX   {mix}")
    total = sum(d.monthly_eur for d in decisions)
    naive = sum(d.economics[Mode.REPLICATE].monthly_eur for d in decisions if d.economics)
    lines.append(
        f"COST  €{total:,.0f}/month as decided  ·  €{naive:,.0f}/month if everything "
        f"were replicated  ·  {(1 - total / naive) * 100:,.0f}% avoided"
    )
    constrained = [d for d in decisions if d.mode is Mode.KEEP_IN_SAP]
    if constrained:
        lines.append(
            f"HELD  {len(constrained)} object(s) stay in SAP on constraints, not cost: "
            + ", ".join(d.object_id for d in constrained)
        )
    return "\n".join(lines)


def _fmt_eur(v: float) -> str:
    return f"€{v:,.0f}"


def decision_register(decisions: list[Decision], cat: Catalog) -> str:
    by_id = {o.id: o for o in cat.objects}
    counts = Counter(d.mode for d in decisions)
    total = sum(d.monthly_eur for d in decisions)
    naive = sum(d.economics[Mode.REPLICATE].monthly_eur for d in decisions if d.economics)

    out: list[str] = []
    out.append("# Decision register — what crosses the seam, and how\n")
    out.append(
        "Generated by `make decide`. One row per object, each carrying the rule that "
        "decided it and the reason in plain language. Regenerate after any change to "
        "`config/` — the register is an output, never edited by hand.\n"
    )
    out.append(
        f"**Landscape.** {len(decisions)} objects · SAP Business Data Cloud / Datasphere "
        f"(`{cat.landscape.sap.datasphere_space}`, {cat.landscape.sap.bdc_tenant_region}) → "
        f"{cat.landscape.target.platform} ({cat.landscape.target.region}).\n"
    )

    out.append("## Outcome\n")
    out.append("| Mode | Objects | Monthly |")
    out.append("|---|---:|---:|")
    for m in _MODE_ORDER:
        sel = [d for d in decisions if d.mode is m]
        if not sel:
            continue
        out.append(f"| {m.value} | {len(sel)} | {_fmt_eur(sum(d.monthly_eur for d in sel))} |")
    out.append(f"| **Total** | **{len(decisions)}** | **{_fmt_eur(total)}** |")
    out.append("")
    out.append(
        f"Replicating everything — the default that needs no architect — would cost "
        f"{_fmt_eur(naive)}/month against {_fmt_eur(total)}/month as decided: "
        f"**{(1 - total / naive) * 100:,.0f}% avoided**, before counting the "
        f"{counts.get(Mode.REPLICATE, 0)} pipelines somebody would then have to operate.\n"
    )

    out.append("## Decisions\n")
    out.append("| Object | Domain | Size | Delta | Q/day | Mode | Rule | €/month | Crossover |")
    out.append("|---|---|---:|---|---:|---|---|---:|---:|")
    for d in decisions:
        obj = by_id[d.object_id]
        x = (
            f"{d.crossover_queries_per_day:,.0f}/day"
            if d.crossover_queries_per_day is not None
            else "—"
        )
        out.append(
            f"| `{d.object_id}` | {d.domain} | {obj.size_gb:,.1f} GB | "
            f"{obj.delta_capability} | {obj.consumer.queries_per_day:,.0f} | "
            f"**{d.mode.value}** | {d.rule_id} | {_fmt_eur(d.monthly_eur)} | {x} |"
        )
    out.append("")

    out.append("## Reasoning, object by object\n")
    for d in decisions:
        obj = by_id[d.object_id]
        out.append(f"### `{d.object_id}` — {d.object_name}\n")
        out.append(
            f"**{d.mode.value}** ({d.rule_id}, {d.direction}). {d.primary_reason}.\n"
        )
        if d.eliminated:
            out.append("Eliminated:\n")
            for m, why in d.eliminated.items():
                out.append(f"- **{m.value}** — {why}.")
            out.append("")
        if d.economics:
            out.append("| Mode | Fixed €/month | Variable €/query | Total €/month | p95 | Freshness |")
            out.append("|---|---:|---:|---:|---:|---:|")
            for m in (Mode.SHARE, Mode.REPLICATE, Mode.FEDERATE):
                e = d.economics[m]
                mark = " ✓" if m is d.mode or (d.mode is Mode.HYBRID and m is Mode.REPLICATE) else ""
                out.append(
                    f"| {m.value}{mark} | {_fmt_eur(e.fixed_eur_month)} | "
                    f"€{e.variable_eur_per_query:,.4f} | {_fmt_eur(e.monthly_eur)} | "
                    f"{e.p95_latency_seconds:,.1f}s | {e.freshness_minutes:,.0f} min |"
                )
            out.append("")
        if d.crossover_queries_per_day is not None:
            verdict = (
                "above it" if obj.consumer.queries_per_day > d.crossover_queries_per_day
                else "below it"
            )
            out.append(
                f"Crossover: replication overtakes federation at "
                f"**{d.crossover_queries_per_day:,.0f} queries/day**; this object runs "
                f"{obj.consumer.queries_per_day:,.0f}/day — {verdict}.\n"
            )
        for n in d.notes:
            out.append(f"> {n}\n")
        if d.flags:
            out.append("Flags: " + ", ".join(f"`{f}`" for f in d.flags) + "\n")

    out.append("---\n")
    out.append(
        "Costs come from `config/cost_model.yaml`, whose numbers are illustrative "
        "order-of-magnitude placeholders, not quotes. Replace them with a real rate "
        "card and re-run: the decisions that move under real rates are the decisions "
        "that were never really about architecture.\n"
    )
    return "\n".join(out)


def crossover_chart(decisions: list[Decision], cat: Catalog, path: Path) -> Path:
    """One object's three cost lines, and where they cross.

    Drawn for the largest object that has all three modes costed — the crossover
    is easiest to argue about where the stakes are highest.
    """
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    by_id = {o.id: o for o in cat.objects}
    candidates = [d for d in decisions if d.economics]
    target = max(candidates, key=lambda d: by_id[d.object_id].size_gb)
    obj = by_id[target.object_id]

    qs = [q for q in range(0, 1501, 10)]
    fig, ax = plt.subplots(figsize=(9, 5))
    styles = {
        Mode.REPLICATE: ("#1f4e79", "-"),
        Mode.FEDERATE: ("#b45309", "--"),
        Mode.SHARE: ("#166534", "-."),
    }
    for m, (color, ls) in styles.items():
        ax.plot(
            qs,
            cost_curve(target.economics[m], [float(q) for q in qs]),
            label=m.value.title(),
            color=color,
            linestyle=ls,
            linewidth=2,
        )

    # Two crossovers matter, not one. Replicate-vs-federate is the classic
    # trade-off; replicate-vs-share is the one that shows zero-copy is not a free
    # lunch — it wins until the object gets hot, and then it loses.
    marks = [
        (target.crossover_queries_per_day, "replicate overtakes federate", 0.12),
        (
            crossover_queries_per_day(
                target.economics[Mode.REPLICATE], target.economics[Mode.SHARE]
            ),
            "replicate overtakes share",
            0.30,
        ),
    ]
    for x, label, height in marks:
        if x is None or not 0 < x < qs[-1]:
            continue
        ax.axvline(x, color="#6b7280", linewidth=1, linestyle=":")
        ax.annotate(
            f"{label} · {x:,.0f} q/day",
            xy=(x, 0),
            xytext=(x + 25, ax.get_ylim()[1] * height),
            color="#374151",
            fontsize=9,
        )
    ax.axvline(obj.consumer.queries_per_day, color="#111827", linewidth=1.2)
    ax.annotate(
        f"actual · {obj.consumer.queries_per_day:,.0f} q/day",
        xy=(obj.consumer.queries_per_day, 0),
        xytext=(obj.consumer.queries_per_day + 25, ax.get_ylim()[1] * 0.75),
        fontsize=9,
    )

    ax.set_title(
        f"{obj.id} — cost of the same data by integration mode\n"
        f"{obj.size_gb:,.0f} GB · {obj.daily_delta_gb:,.1f} GB/day delta · "
        f"{obj.delta_capability} extraction",
        fontsize=11,
    )
    ax.set_xlabel("consumer queries per day")
    ax.set_ylabel(f"modelled {cat.costs.currency} per month")
    ax.legend(frameon=False)
    ax.grid(alpha=0.25, linewidth=0.6)
    ax.set_xlim(0, qs[-1])
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=144)
    plt.close(fig)
    return path


def mode_mix_chart(decisions: list[Decision], cat: Catalog, path: Path) -> Path:
    """Monthly cost as decided versus replicate-everything, by domain."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    domains = sorted({d.domain for d in decisions})
    decided = [
        sum(d.monthly_eur for d in decisions if d.domain == dom) for dom in domains
    ]
    naive = [
        sum(d.economics[Mode.REPLICATE].monthly_eur for d in decisions
            if d.domain == dom and d.economics)
        for dom in domains
    ]

    fig, ax = plt.subplots(figsize=(9, 4.5))
    xs = range(len(domains))
    ax.bar([x - 0.2 for x in xs], naive, width=0.4, label="replicate everything",
           color="#cbd5e1")
    ax.bar([x + 0.2 for x in xs], decided, width=0.4, label="as decided",
           color="#1f4e79")
    ax.set_xticks(list(xs))
    ax.set_xticklabels([d.replace("_", " ") for d in domains])
    ax.set_ylabel(f"modelled {cat.costs.currency} per month")
    ax.set_title("What the decision is worth, by domain", fontsize=11)
    ax.legend(frameon=False)
    ax.grid(axis="y", alpha=0.25, linewidth=0.6)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=144)
    plt.close(fig)
    return path


def write_all(decisions: list[Decision], cat: Catalog, reports: Path | None = None) -> list[Path]:
    out = Path(reports) if reports else REPORTS
    out.mkdir(parents=True, exist_ok=True)
    written = [out / "decisions.md"]
    written[0].write_text(decision_register(decisions, cat), encoding="utf-8")
    written.append(crossover_chart(decisions, cat, out / "crossover.png"))
    written.append(mode_mix_chart(decisions, cat, out / "mode-mix.png"))
    return written


__all__ = [
    "DAYS_PER_MONTH",
    "console_summary",
    "crossover_chart",
    "decision_register",
    "mode_mix_chart",
    "write_all",
]
